# Base configs
baseurl: "https://arlomemes.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Arlo Memes"
subtitle: "Embarrassing him before he can fight back"
author: "Zach & Shelli"
header:
 title: "Arlo Memes"
 subtitle: "Sorry, kiddo"
footer:
 name: "Hey there, my name is Zach"
 bio: "I am trolling my infant son."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "ZS"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
